name: CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/dev'
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mayarasb
            -Dsonar.projectKey=Mayarasb_api-sast-P2-IEC
            -Dsonar.sources=.


      - name: Calculate version (only on main)
        id: ver
        if: github.ref == 'refs/heads/main'
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r MAJ MIN PATCH <<< "${TAG#v}"
          PATCH=$((PATCH+1))
          NEW_TAG="v${MAJ}.${MIN}.${PATCH}"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push Git tag (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.ver.outputs.new_tag }}
          git push origin ${{ steps.ver.outputs.new_tag }}

      - name: Create GitHub Release (only on main)
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.ver.outputs.new_tag }}
          name: Release ${{ steps.ver.outputs.new_tag }}
          body: |
            ðŸš€ Nova release gerada automaticamente!
            Tag: ${{ steps.ver.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Login to Docker Hub (only on main)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-sast:${{ steps.ver.outputs.new_tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-sast:${{ steps.ver.outputs.new_tag }}
