name: CI/CD pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/api-sast-p2-iec

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2

        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Calculate version (semantic / tag)
        id: ver
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r MAJ MIN PATCH <<< "${TAG#v}"
          PATCH=$((PATCH+1))
          NEW_TAG="v${MAJ}.${MIN}.${PATCH}"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # Pega a nova tag
          NEW_TAG=${{ steps.ver.outputs.new_tag }}

          # Verifica se a tag jÃ¡ existe
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
            echo "Tag $NEW_TAG already exists, skipping..."
          else
            git tag "$NEW_TAG"
            git push origin "$NEW_TAG"
          fi

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.ver.outputs.new_tag }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to DockerHub
        run: |
          docker tag $IMAGE_NAME:${{ steps.ver.outputs.new_tag }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.ver.outputs.new_tag }}
          docker push $IMAGE_NAME:latest

      - name: Create GitHub release tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.ver.outputs.new_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy to Render (via API)
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" \
           -d '{"service":"${{ secrets.RENDER_SERVICE_ID }}", "image":"'"${{ secrets.DOCKERHUB_USERNAME }}/api-sast-p2-iec:${{ steps.ver.outputs.new_tag }}"'"}' \
           "https://api.render.com/deploys"
